[project]
name = "replearningbook"
version = "0.1.0"
description = "Files to run experiments for the book."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.6.2",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "optax>=0.2.5",
    "pyright>=1.1.403",
    "torchvision>=0.22.1",
    "tqdm>=4.67.1",
]
